language: android
jdk: oraclejdk8
sudo: false
android:
  components:
    # Update Android SDK Tools
    - tools
    - platform-tools

    - build-tools-25.0.2
    - android-25
    - android-19
    # Support library
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository

before_script:
    - "echo $JAVA_OPTS"
    - "export JAVA_OPTS=-Xmx512m"

script:
    - ./gradlew build jacocoTestReportDebug

after_success:
    - bash <(curl -s https://codecov.io/bash)